# Generated by Django 3.1.1 on 2020-09-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20200908_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
